openapi: 3.2.0
info:
  version: 20.17.1
  title: Pod App Entitlement API
  description: 'This document refers to Symphony API calls that do not need

    encryption or decryption of content.'
servers:
- url: https://yourpodURL.symphony.com/pod
tags:
- name: App Entitlement
paths:
  /v1/admin/app/entitlement/list:
    get:
      summary: Get the list of application entitlements for the company
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - App Entitlement
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PodAppEntitlementList'
              example:
              - appId: djApp
                appName: Dow Jones
                enable: true
                listed: true
                install: true
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1AdminAppEntitlementList
      x-operation-id-source: derived
    post:
      summary: Update the application entitlements for the company
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - App Entitlement
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PodAppEntitlementList'
              example:
              - appId: djApp
                appName: Dow Jones
                enable: true
                listed: true
                install: false
              - appId: spcapiq
                appName: S&P Capital IQ Data
                enable: true
                listed: true
                install: false
              - appId: selerity
                appName: Selerity Context
                enable: false
                listed: true
                install: true
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PodAppEntitlementList'
        required: true
      operationId: postV1AdminAppEntitlementList
      x-operation-id-source: derived
  /v1/admin/user/{uid}/app/entitlement/list:
    get:
      summary: Get the list of application entitlements for this user
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: uid
        description: User ID as a decimal integer
        in: path
        required: true
        schema:
          type: integer
          format: int64
      tags:
      - App Entitlement
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAppEntitlementList'
              example:
              - appId: djApp
                appName: Dow Jones
                listed: true
                install: false
              - appId: selerity
                appName: Selerity Context
                listed: true
                install: true
                products:
                - appId: selerity
                  name: Standard
                  subscribed: true
                  type: default
                - appId: selerity
                  name: Premium
                  sku: AcDccU53SsY
                  subscribed: false
                  type: premium
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1AdminUserByUidAppEntitlementList
      x-operation-id-source: derived
    post:
      summary: Update the application entitlements for this user
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: uid
        description: User ID as a decimal integer
        in: path
        required: true
        schema:
          type: integer
          format: int64
      tags:
      - App Entitlement
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAppEntitlementList'
              example:
              - appId: djApp
                appName: Dow Jones
                listed: true
                install: false
              - appId: selerity
                appName: Selerity Context
                listed: true
                install: true
                products:
                - appId: selerity
                  name: Standard
                  subscribed: true
                  type: default
                - appId: selerity
                  name: Premium
                  sku: AcDccU53SsY
                  subscribed: false
                  type: premium
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAppEntitlementList'
        required: true
      operationId: postV1AdminUserByUidAppEntitlementList
      x-operation-id-source: derived
    patch:
      summary: Update unique entitlement of an app for this user.
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: uid
        description: User ID as a decimal integer
        in: path
        required: true
        schema:
          type: integer
          format: int64
      tags:
      - App Entitlement
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAppEntitlementList'
              example:
              - appId: djApp
                appName: Dow Jones
                listed: true
                install: false
              - appId: selerity
                appName: Selerity Context
                listed: true
                install: true
                products:
                - appId: selerity
                  name: Standard
                  subscribed: true
                  type: default
                - appId: selerity
                  name: Premium
                  sku: AcDccU53SsY
                  subscribed: false
                  type: premium
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAppEntitlementsPatchList'
        required: true
      operationId: patchV1AdminUserByUidAppEntitlementList
      x-operation-id-source: derived
components:
  schemas:
    UserAppEntitlementList:
      type: array
      items:
        $ref: '#/components/schemas/UserAppEntitlement'
      example:
      - appId: djApp
        appName: Dow Jones
        listed: true
        install: false
      - appId: selerity
        appName: Selerity Context
        listed: true
        install: true
        products:
        - appId: selerity
          name: Standard
          subscribed: true
          type: default
        - appId: selerity
          name: Premium
          sku: AcDccU53SsY
          subscribed: false
          type: premium
    UserAppEntitlementPatch:
      description: Application Entitlements to patch for the user
      type: object
      required:
      - appId
      properties:
        appId:
          type: string
          description: Unique ID for the Application
          maxLength: 256
          minLength: 1
          example: selerity
        listed:
          type: string
          enum:
          - 'TRUE'
          - 'FALSE'
          - KEEP
          - REMOVE
          default: KEEP
          description: If "TRUE", this application will be listed in the appstore for this user. If "FALSE", this application will be hidden in the appstore. If "KEEP" or not set, the current value is kept. If "REMOVE", it will be removed from user settings and the pod level setting's value will be used.
          example: KEEP
        install:
          type: string
          enum:
          - 'TRUE'
          - 'FALSE'
          - KEEP
          - REMOVE
          default: KEEP
          description: If "TRUE", this application will be installed for this user. If "FALSE", this application will not be installed for this user. If "KEEP" or not set, the current value is kept. If "REMOVE", it will be removed from user settings and the pod level setting's value will be used.
          example: true
        product:
          $ref: '#/components/schemas/Product'
    PodAppEntitlement:
      description: Application Entitlements for the company
      type: object
      required:
      - appId
      - appName
      - enable
      - listed
      - install
      properties:
        appId:
          type: string
          description: Unique ID for the Application
          maxLength: 256
          minLength: 1
          example: djApp
        appName:
          type: string
          description: Name for this Application
          maxLength: 50
          minLength: 1
          example: Dow Jones
        enable:
          type: boolean
          example: true
        listed:
          type: boolean
          description: if true, this application will be listed in the appstore for everyone.  Otherwise, this application will be hidden in the appstore.
          example: true
        install:
          type: boolean
          description: if true, the entitlement is set to automatic for the company.  Otherwise, it is set to manual.
          example: true
    ProductList:
      type: array
      items:
        $ref: '#/components/schemas/Product'
      example:
      - appId: selerity
        name: Standard
        subscribed: true
        type: default
      - appId: selerity
        name: Premium
        sku: AcDccU53SsY
        subscribed: false
        type: premium
    UserAppEntitlement:
      description: Application Entitlements for the user
      type: object
      required:
      - appId
      - listed
      - install
      properties:
        appId:
          type: string
          description: Unique ID for the Application
          maxLength: 256
          minLength: 1
          example: selerity
        appName:
          type: string
          description: Name for this Application
          maxLength: 50
          minLength: 1
          example: Selerity Context
        listed:
          type: boolean
          description: if true, this application will be listed in the appstore for this user.  Otherwise, this application will be hidden in the appstore.
          example: true
        install:
          type: boolean
          description: if true, it indicate this application is installed for this user.  Otherwise, this user does not have this application installed.
          example: true
        products:
          $ref: '#/components/schemas/ProductList'
    Product:
      description: Application Product
      type: object
      required:
      - name
      - type
      - subscribed
      properties:
        appId:
          type: string
          description: App ID for the Product
          maxLength: 256
          minLength: 1
          example: selerity
        name:
          type: string
          minLength: 1
          maxLength: 50
          description: Product Name
          example: Premium
        sku:
          type: string
          minLength: 1
          maxLength: 100
          description: Product SKU
          example: AcDccU53SsY
        subscribed:
          type: boolean
          description: indicate whether the product is subscribed or not
          example: false
        type:
          type: string
          description: Product Type (default or premium)
          example: premium
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 401
        message:
          type: string
          example: Invalid session
    PodAppEntitlementList:
      type: array
      items:
        $ref: '#/components/schemas/PodAppEntitlement'
      example:
      - appId: djApp
        appName: Dow Jones
        enable: true
        listed: true
        install: false
      - appId: selerity
        appName: Selerity Context
        enable: false
        listed: true
        install: true
    UserAppEntitlementsPatchList:
      description: Array of app entitlements to patch for a user
      type: array
      items:
        $ref: '#/components/schemas/UserAppEntitlementPatch'
