openapi: 3.2.0
info:
  version: 20.17.1
  title: Pod Message API
  description: 'This document refers to Symphony API calls that do not need

    encryption or decryption of content.'
servers:
- url: https://yourpodURL.symphony.com/pod
tags:
- name: Message
paths:
  /v1/message/{mid}/status:
    get:
      summary: Get the read status of a particular message
      parameters:
      - name: mid
        description: Message ID
        in: path
        required: true
        schema:
          type: string
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - Message
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageStatus'
              example:
                author:
                  userId: 7078106103901
                  firstName: Gustav
                  lastName: Mahler
                  displayName: Gustav Mahler
                  email: gustav.mahler@music.org
                  userName: gmahler
                  timestamp: 1531968487845
                read:
                - userId: 7078106103901
                  firsName: Gustav
                  lastName: Mahler
                  displayName: Gustav Mahler
                  email: gustav.mahler@music.org
                  userName: gmahler
                  timestamp: 1489769156271
                - userId: 7078106103902
                  firsName: Hildegard
                  lastName: Bingen
                  displayName: Hildegard Bingen
                  email: hildegard.bingen@music.org
                  userName: hbingen
                  timestamp: 1487352923000
                delivered:
                - userId: 7078106103903
                  firsName: Franz
                  lastName: Liszt
                  displayName: Franz Liszt
                  email: franz.liszt@music.org
                  userName: fliszt
                  timestamp: 1484674523000
                sent:
                - userId: 7078106103904
                  firsName: Benjamin
                  lastName: Britten
                  displayName: Benjamin Britten
                  email: benjamin.britten@music.org
                  userName: bbritten
                  timestamp: 1484156123000
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '404':
          description: 'Not Found: Message ID does not exist.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: // Not Found. Message ID does not exist. See response body for fruther details.
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1MessageByMidStatus
      x-operation-id-source: derived
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 401
        message:
          type: string
          example: Invalid session
    MessageStatusUser:
      type: object
      properties:
        userId:
          type: string
          example: 7078106103901
        firstName:
          type: string
          example: Gustav
        lastName:
          type: string
          example: Mahler
        displayName:
          type: string
          example: Gustav Mahler
        email:
          type: string
          example: gustav.mahler@music.org
        userName:
          type: string
          example: gmahler
        timestamp:
          type: string
          example: 1531968487845
    MessageStatus:
      description: 'Holds the status of a particular message, indicating which user the message has been sent, delivered or read.

        '
      type: object
      properties:
        author:
          description: User who has sent the message.
          type: object
          $ref: '#/components/schemas/MessageStatusUser'
        read:
          description: All users who have read that message, in any Symphony client.
          type: array
          items:
            $ref: '#/components/schemas/MessageStatusUser'
        delivered:
          description: 'All users who have at least one Symphony client to which the message has been delivered, and not read yet.

            '
          type: array
          items:
            $ref: '#/components/schemas/MessageStatusUser'
        sent:
          description: 'All users to whom the message has been sent and received by the Symphony system,

            but not yet delivered to any user''s Symphony client.

            '
          type: array
          items:
            $ref: '#/components/schemas/MessageStatusUser'
          example:
          - userId: 7078106103904
            firsName: Benjamin
            lastName: Britten
            displayName: Benjamin Britten
            email: benjamin.britten@music.org
            userName: bbritten
            timestamp: 1484156123000
          - userId: 7078106103901
            firsName: Gustav
            lastName: Mahler
            displayName: Gustav Mahler
            email: gmahler@music.org
            userName: gmahler
            timestamp: 1531968487845
