openapi: 3.2.0
info:
  version: 20.17.1
  title: Pod Connection API
  description: 'This document refers to Symphony API calls that do not need

    encryption or decryption of content.'
servers:
- url: https://yourpodURL.symphony.com/pod
tags:
- name: Connection
paths:
  /v1/connection/list:
    get:
      summary: List of requesting user's connection
      description: 'This retrieves all connections of the requesting user. (i.e. both connections in which the requesting user is the sender and those

        in which the requesting user is the inivtee) By default, if you haven''t specified the connection status to filter on, this call will only

        return results for both "pending_incoming" and "pending_outgoing". You can optionally filter by userIds to further restrict the results of

        a specific connection status. If the users are in the same private pod, the users have an implicit connection status of "accepted". Those

        users will not be returned in the response if you don''t specify the connection status as "accepted" (default is "pending")

        and the explicit userIds in the request.'
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: status
        description: 'Filter the connection list based on the connection status.

          The connection status can only be pending_incoming, pending_outgoing, accepted, rejected, or all (all of the above)

          '
        in: query
        schema:
          type: string
          enum:
          - PENDING_INCOMING
          - PENDING_OUTGOING
          - ACCEPTED
          - REJECTED
          - ALL
      - name: userIds
        description: 'The userIds parameter should be specified as a comma delimited list of user ids and can be used to restrict the results of a specific connection.

          Note that this is particularly important if the caller intends to retrieve results for implicit connection (user within the same pod).

          Implicit connections will not be included in the response if userId is not provided.

          '
        in: query
        schema:
          type: string
      tags:
      - Connection
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserConnectionList'
              example:
              - userId: 769658112378
                status: ACCEPTED
                updatedAt: 1471018076255
              - userId: 7078106103809
                status: PENDING_INCOMING
                updatedAt: 1467562406219
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '404':
          description: 'Not Found: Connection cannot be found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: // Not Found. Connection cannot be found. See response body for fruther details.
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1ConnectionList
      x-operation-id-source: derived
  /v1/connection/create:
    post:
      summary: Sends an invitation to connect with another user
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - Connection
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserConnection'
              example:
                userId: 7078106126503
                status: PENDING_OUTGOING
                firstRequestedAt: 1470018076306
                updatedAt: 1471018076255
                requestCounter: 1
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '404':
          description: 'Not Found: User cannot be found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: // Not Found. User cannot be found. See response body for fruther details.
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserConnectionRequest'
        required: true
      operationId: postV1ConnectionCreate
      x-operation-id-source: derived
  /v1/connection/accept:
    post:
      summary: Accept the connection request for the requesting user
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - Connection
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserConnection'
              example:
                userId: 7078106126503
                status: ACCEPTED
                firstRequestedAt: 1470018076306
                updatedAt: 1471018076255
                requestCounter: 1
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '404':
          description: 'Not Found: Connection cannot be found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: // Not Found. Connection cannot be found. See response body for fruther details.
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserConnectionRequest'
        required: true
      operationId: postV1ConnectionAccept
      x-operation-id-source: derived
  /v1/connection/reject:
    post:
      summary: Reject the connection request for the requesting user
      description: 'Reject the connection between the requesting user and request sender. If both users are in the same private pod,

        an error will be returned because both users have an implicit connection which cannot be rejected.'
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - Connection
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserConnection'
              example:
                userId: 7078106126503
                status: REJECTED
                firstRequestedAt: 1470018076306
                updatedAt: 1471018076255
                requestCounter: 1
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '404':
          description: 'Not Found: Connection cannot be found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: // Not Found. Connection cannot be found. See response body for fruther details.
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserConnectionRequest'
        required: true
      operationId: postV1ConnectionReject
      x-operation-id-source: derived
  /v1/connection/user/{userId}/info:
    get:
      summary: The status of the connection invitation to another user
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: userId
        description: user Id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Connection
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserConnection'
              example:
                userId: 769658112378
                status: ACCEPTED
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '404':
          description: 'Not Found: Connection cannot be found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: // Not Found. Connection cannot be found. See response body for fruther details.
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1ConnectionUserByUserIdInfo
      x-operation-id-source: derived
  /v1/connection/user/{uid}/remove:
    post:
      summary: Removes a connection with a user
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: uid
        description: 'User ID as a decimal integer

          '
        in: path
        required: true
        schema:
          type: integer
          format: int64
      tags:
      - Connection
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                format: TEXT
                message: Connection Removed.
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '404':
          description: 'Not Found: Connection cannot be found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: // Not Found. Connection cannot be found. See response body for fruther details.
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: postV1ConnectionUserByUidRemove
      x-operation-id-source: derived
components:
  schemas:
    UserConnection:
      type: object
      description: Connection status between two users
      properties:
        userId:
          type: integer
          format: int64
          description: user id
          example: 769658112378
        status:
          type: string
          description: Connection status between the requesting user and the request sender
          enum:
          - PENDING_INCOMING
          - PENDING_OUTGOING
          - ACCEPTED
          - REJECTED
          example: ACCEPTED
        firstRequestedAt:
          type: integer
          format: int64
          description: unix timestamp when the first request was made
          example: 1470018073812
        updatedAt:
          type: integer
          format: int64
          description: unix timestamp on the last updated date
          example: 1471018076255
        requestCounter:
          type: integer
          format: int32
          description: number of requests made
          example: 1
    UserConnectionRequest:
      type: object
      description: Request body for the Connection APIs
      properties:
        userId:
          type: integer
          format: int64
          description: user id
          example: 769658112378
    UserConnectionList:
      type: array
      items:
        $ref: '#/components/schemas/UserConnection'
      example:
      - userId: 769658112378
        status: PENDING_OUTGOING
        firstRequestedAt: 1470018073812
        updatedAt: 1471018076255
        requestCounter: 1
      - userId: 7078106103809
        status: ACCEPTED
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 401
        message:
          type: string
          example: Invalid session
    SuccessResponse:
      type: object
      properties:
        format:
          type: string
          enum:
          - TEXT
          - XML
          example: TEXT
        message:
          type: string
          example: Success
