openapi: 3.2.0
info:
  version: 20.17.1
  title: Pod Security API
  description: 'This document refers to Symphony API calls that do not need

    encryption or decryption of content.'
servers:
- url: https://yourpodURL.symphony.com/pod
tags:
- name: Security
paths:
  /v1/companycert/list:
    get:
      summary: List all trusted certs
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: skip
        description: Pagination start
        in: query
        required: false
        schema:
          type: integer
      - name: limit
        description: Row limit
        in: query
        required: false
        schema:
          type: integer
      tags:
      - Security
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyCertInfoList'
              example:
              - companyCertAttributes:
                  name: agentservice
                  type:
                    type: USER
                  status:
                    type: TRUSTED
                companyCertInfo:
                  fingerPrint: 300a...
                  lastSeen: 0
                  updatedAt: 0
                  updatedBy: 0
                  commonName: agentservice
                  expiryDate: 1781886755000
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1CompanycertList
      x-operation-id-source: derived
  /v2/companycert/create:
    post:
      summary: Create a company trusted or untrusted certificate.
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - Security
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyCertDetail'
              example:
              - companyCertAttributes:
                  name: jira
                  type:
                    type: USER
                  status:
                    type: KNOWN
                companyCertInfo:
                  fingerPrint: 450369...
                  issuerFingerPrint: c35680...
                  lastSeen: 1529994790226
                  updatedAt: 1529598066602
                  updatedBy: 9208409884327
                  commonName: jiraWebHookIntegration
                  expiryDate: 1768510565000
                certInfo:
                - name: General
                  attributes:
                  - name: Issuer
                    value: C=US O=Symphony Communications LLC CN=bot_user_provisioning
                  - name: Subject
                    value: C=US OU=NOT FOR PRODUCTION USE O=Symphony Communications LLC CN=jiraWebHookIntegration
                  - name: Signature Algorithm
                    value: SHA256withRSA
                - name: Validity
                  attributes:
                  - name: Not Before
                    value: Mon Jan 15 20:56:05 UTC 2018
                  - name: Not After
                    value: Thu Jan 15 20:56:05 UTC 2026
                - name: Public Key
                  attributes:
                  - name: Algorithm
                    value: RSA
                  - name: Format
                    value: X.509
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyCert'
        required: true
      operationId: postV2CompanycertCreate
      x-operation-id-source: derived
  /v1/companycert/delete:
    post:
      summary: Delete a company certificate
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - Security
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                format: TEXT
                message: OK
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StringId'
        required: true
      operationId: postV1CompanycertDelete
      x-operation-id-source: derived
  /v1/companycert/{fingerPrint}/get:
    get:
      summary: Get the details of a company certificate
      parameters:
      - name: fingerPrint
        description: Certificate fingerPrint (ID)
        in: path
        required: true
        schema:
          type: string
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - Security
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyCertDetail'
              example:
              - companyCertAttributes:
                  name: jira
                  type:
                    type: USER
                  status:
                    type: KNOWN
                companyCertInfo:
                  fingerPrint: 450369...
                  issuerFingerPrint: c35680...
                  lastSeen: 1529994790226
                  updatedAt: 1529598066602
                  updatedBy: 9208409884327
                  commonName: jiraWebHookIntegration
                  expiryDate: 1768510565000
                certInfo:
                - name: General
                  attributes:
                  - name: Issuer
                    value: C=US O=Symphony Communications LLC CN=bot_user_provisioning
                  - name: Subject
                    value: C=US OU=NOT FOR PRODUCTION USE O=Symphony Communications LLC CN=jiraWebHookIntegration
                  - name: Signature Algorithm
                    value: SHA256withRSA
                - name: Validity
                  attributes:
                  - name: Not Before
                    value: Mon Jan 15 20:56:05 UTC 2018
                  - name: Not After
                    value: Thu Jan 15 20:56:05 UTC 2026
                - name: Public Key
                  attributes:
                  - name: Algorithm
                    value: RSA
                  - name: Format
                    value: X.509
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1CompanycertByFingerPrintGet
      x-operation-id-source: derived
  /v1/companycert/{fingerPrint}/update:
    post:
      summary: Update a company certificate
      parameters:
      - name: fingerPrint
        description: Certificate fingerPrint (ID)
        in: path
        required: true
        schema:
          type: string
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - Security
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                format: TEXT
                message: OK
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyCertAttributes'
        required: true
      operationId: postV1CompanycertByFingerPrintUpdate
      x-operation-id-source: derived
  /v1/companycert/{fingerPrint}/issuedBy:
    get:
      summary: Return a list of all certificates which were verified to the cert whose…
      parameters:
      - name: fingerPrint
        description: Certificate fingerPrint (ID)
        in: path
        required: true
        schema:
          type: string
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - Security
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyCertInfoList'
              example:
              - companyCertAttributes:
                  name: agentservice
                  type:
                    type: USER
                  status:
                    type: TRUSTED
                companyCertInfo:
                  fingerPrint: 300a...
                  lastSeen: 0
                  updatedAt: 0
                  updatedBy: 0
                  commonName: agentservice
                  expiryDate: 1781886755000
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1CompanycertByFingerPrintIssuedBy
      x-operation-id-source: derived
  /v1/companycert/podmanaged/list:
    get:
      summary: List all trusted certs
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: skip
        description: Pagination start
        in: query
        required: false
        schema:
          type: integer
      - name: limit
        description: Row limit
        in: query
        required: false
        schema:
          type: integer
      tags:
      - Security
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyCertInfoList'
              example:
              - companyCertAttributes:
                  name: agentservice
                  type:
                    type: USER
                  status:
                    type: TRUSTED
                companyCertInfo:
                  fingerPrint: 300a...
                  lastSeen: 0
                  updatedAt: 0
                  updatedBy: 0
                  commonName: agentservice
                  expiryDate: 1781886755000
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1CompanycertPodmanagedList
      x-operation-id-source: derived
  /v1/companycert/type/list:
    post:
      summary: List all certs of the given types
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: skip
        description: Pagination start
        in: query
        required: false
        schema:
          type: integer
      - name: limit
        description: Row limit
        in: query
        required: false
        schema:
          type: integer
      tags:
      - Security
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyCertInfoList'
              example:
              - companyCertAttributes:
                  name: agentservice
                  type:
                    type: USER
                  status:
                    type: TRUSTED
                companyCertInfo:
                  fingerPrint: 300a...
                  lastSeen: 0
                  updatedAt: 0
                  updatedBy: 0
                  commonName: agentservice
                  expiryDate: 1781886755000
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyCertTypeList'
        description: Certificate type list
        required: true
      operationId: postV1CompanycertTypeList
      x-operation-id-source: derived
components:
  schemas:
    CompanyCertAttributes:
      type: object
      properties:
        name:
          type: string
          description: Friendly name assigned by administrator
          example: agentservice
        type:
          $ref: '#/components/schemas/CompanyCertType'
        status:
          $ref: '#/components/schemas/CompanyCertStatus'
    CompanyCert:
      type: object
      properties:
        pem:
          type: string
          description: An X509 certificate in PEM format
          example: '-----BEGIN CERTIFICATE-----MIIH/TC...p9DBiB/-----END CERTIFICATE-----'
        attributes:
          $ref: '#/components/schemas/CompanyCertAttributes'
    CompanyCertInfo:
      type: object
      properties:
        fingerPrint:
          type: string
          description: Unique identifier
          example: 300a...
        issuerFingerPrint:
          type: string
          description: Unique identifier of issuer cert if known
          example: 450s...
        lastSeen:
          type: integer
          format: int64
          description: Date when we last saw this certificate presented
          example: 0
        updatedAt:
          type: integer
          format: int64
          description: Date when this cert was last updated by administrator
          example: 0
        updatedBy:
          type: integer
          format: int64
          description: User ID of administrator who last updated this cert
          example: 0
        commonName:
          type: string
          description: The Symphony account name which this certificate authenticates
          example: agentservice
        expiryDate:
          type: integer
          format: int64
          description: Expiry date of this cert
          example: 1781886755000
    CertInfoItem:
      type: object
      properties:
        name:
          type: string
          example: Public Key
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/NameValuePair'
          example:
          - name: Algorithm
            value: RSA
          - name: Format
            value: X.509
    StringId:
      type: object
      properties:
        id:
          type: string
          example: xhGxbTcvTDK6EIMMrwdOrX___quztr2HdA
    CompanyCertType:
      type: object
      properties:
        type:
          type: string
          enum:
          - USERSIGNING
          - USER
          - OPERATIONSSIGNING
          - OPERATIONSUSER
          example: USER
    CompanyCertDetail:
      type: object
      properties:
        companyCertAttributes:
          $ref: '#/components/schemas/CompanyCertAttributes'
        companyCertInfo:
          $ref: '#/components/schemas/CompanyCertInfo'
        certInfo:
          $ref: '#/components/schemas/CertInfo'
    CompanyCertTypeList:
      type: array
      items:
        $ref: '#/components/schemas/CompanyCertType'
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 401
        message:
          type: string
          example: Invalid session
    CompanyCertStatus:
      type: object
      properties:
        type:
          type: string
          enum:
          - TRUSTED
          - KNOWN
          - REVOKED
          - DISABLED
          example: TRUSTED
    CertInfo:
      type: array
      items:
        $ref: '#/components/schemas/CertInfoItem'
      example:
      - name: Validity
        attributes:
        - name: Not Before
          value: Mon Jan 15 20:56:05 UTC 2018
        - name: Not After
          value: Thu Jan 15 20:56:05 UTC 2026
      - name: Public Key
        attributes:
        - name: Algorithm
          value: RSA
        - name: Format
          value: X.509
    NameValuePair:
      type: object
      properties:
        name:
          type: string
          example: Algorithm
        value:
          type: string
          example: RSA
    SuccessResponse:
      type: object
      properties:
        format:
          type: string
          enum:
          - TEXT
          - XML
          example: TEXT
        message:
          type: string
          example: Success
    CompanyCertInfoList:
      type: array
      items:
        type: object
        properties:
          companyCertAttributes:
            $ref: '#/components/schemas/CompanyCertAttributes'
          companyCertInfo:
            $ref: '#/components/schemas/CompanyCertInfo'
        example:
        - companyCertAttributes:
            name: agentservice
            type:
              type: USER
            status:
              type: TRUSTED
          companyCertInfo:
            fingerPrint: 300a...
            lastSeen: 0
            updatedAt: 0
            updatedBy: 0
            commonName: agentservice
            expiryDate: 1781886755000
